
### GET registration
GET http://localhost:5000/api/registrations

### POST registration
POST http://localhost:5000/api/registration
Content-Type: application/json;charset=UTF-8

{
        "name":"Bernd Werfel",
        "email":"BerndWerfel@renault.com",
        "phone":"031 745 56 14",
        "priority":"Standard",
        "service":"Heisswachsen",
        "create_date":"2022-11-25T18:12:43.511Z",
        "pickup_date":"2022-12-02T18:12:43.511Z"
}

### Delete
DELETE http://localhost:5000/api/registration/4
